### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by benatwork** [stylepoints/stylepoints#40]
https://developers.google.com/analytics/devguides/collection/analyticsjs/events
https://analytics.google.com/analytics/web/?authuser=0#management/Settings/a88292469w131181123p135051562/%3Fm.page%3DTrackingCode/
```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-88292469-1', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by take0ut** [comment]
@benatwork all i have to do is add this to the html templates?

**Comment by take0ut** [comment]
linked with #44

**Comment by benatwork** [comment]
Yes, that will get us the basic pageview tracking, but we will still need to add any manual event tracking. No sensitive data to worry about in here since the tracking code is linked to the domain.
